-- 웨어하우스 관련~~

INSERT INTO `LOGISTICS_WAREHOUSE` (LOGISTICS_WAREHOUSE_PK,WAREHOUSE_NAME)
VALUES
    (UUID(),'Shin_WAREHOUSE');

INSERT INTO `LOGISTICS_WAREHOUSE_STACK` (`LOGISTICS_WAREHOUSE_SOURCE_PK`, `SOURCE_FK`, `LOGISTICS_WAREHOUSE_FK`, `QUANTITY`)
VALUES
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '소고기'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 100),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '돼지고기'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 150),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '김치'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 200),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '된장'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 250);




-- 상태가 '처리 후'인 주문을 유통 창고 재고에 저장
INSERT INTO LOGISTICS_WAREHOUSE_SOURCE (LOGISTICS_WAREHOUSE_SOURCE_PK, SOURCE_FK, LOGISTICS_WAREHOUSE_FK, QUANTITY)
SELECT
    UUID(),
    sp.SOURCE_ID,
    (SELECT LOGISTICS_WAREHOUSE_PK
     FROM LOGISTICS_WAREHOUSE
     WHERE WAREHOUSE_NAME = 'Shin_WAREHOUSE') AS LOGISTICS_WAREHOUSE_FK,
    po.QUENTITY
FROM
    PRODUCT_ORDER po
        JOIN
    KIT_SOURCE_PRICE ksp ON po.KIT_SOURCE_PRICE_ID = ksp.KIT_SOURCE_PRICE_ID
        JOIN
    SOURCE_PRICE sp ON ksp.SOURCE_PRICE_ID = sp.SOURCE_PRICE_ID
WHERE
    po.STATUS_ID = (SELECT STATUS_ID FROM STATUS WHERE STATUS = '처리 후');