-- 웨어하우스 관련~~

INSERT INTO `LOGISTICS_WAREHOUSE` (LOGISTICS_WAREHOUSE_PK,WAREHOUSE_NAME)
VALUES
    (UUID(),'Shin_WAREHOUSE');

INSERT INTO `LOGISTICS_WAREHOUSE_SOURCE` (`LOGISTICS_WAREHOUSE_SOURCE_PK`, `SOURCE_FK`, `LOGISTICS_WAREHOUSE_FK`, `QUANTITY`)
VALUES
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '소고기'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 100),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '돼지고기'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 150),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '김치'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 200),
    (UUID(), (SELECT `SOURCE_ID` FROM `SOURCE` WHERE `NAME` = '된장'), (SELECT `LOGISTICS_WAREHOUSE_PK`FROM `LOGISTICS_WAREHOUSE`WHERE `WAREHOUSE_NAME` = 'Shin_WAREHOUSE'), 250);
